### ISSUE TITLE
The thunder icon disappears when the user gives input and reappears.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterH5P#61]
**Describe the bug**
In word level the thunder icon disappears when the input is given and re-appears.
**To Reproduce**

1. Start the Apache and MySQL server and open the localhost.
2. In the Curious Learning content go to Feed the Monster game and click on play button.
3. Select Developer mode and go to level selection screen and select word level (Ex. Level 20) and start the game.

**Expected behavior**
The thunder icon should not disappear when input is given.
**Screenshots**
![Screenshot (88).png](https://images.zenhubusercontent.com/623b0e5da1bf54266c59b5e8/9efbdd54-409d-45fe-a6a6-9caed7f62921)
![Screenshot (89).png](https://images.zenhubusercontent.com/623b0e5da1bf54266c59b5e8/10c41328-f65e-48fb-a172-1a13ededdeeb)
**Desktop (please complete the following information):**
• OS: Windows 10
• Browser: Chrome
• Version: N/A
**Additional context**
N/A (edited)

**Comment by burrage** [comment]
For clarity, this is the orange bubble above the monster's head that displays the target answer that the player has to match.
