### ISSUE TITLE
Next level button should not be displayed for zero stars.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterH5P#63]
**Describe the bug**
When the user scores zero stars the next button is displayed at the end of the level.
**To Reproduce**

1. Start the Apache and MySQL server and open the localhost.
2. In the Curious Learning content go to Feed the Monster game and click on play button.
3. Go to level selection screen and play the game and get zero stars.

**Expected behavior**
The next level button should not be displayed for zero stars.
**Screenshots**
![Screenshot (93).png](https://images.zenhubusercontent.com/623b0e5da1bf54266c59b5e8/5ba146cd-59f2-4d64-a097-e9548364eae8)
**Desktop (please complete the following information):**
• OS: Windows 10
• Browser: Chrome
• Version: N/A
**Additional context**
N/A (edited)

**Comment by burrage** [comment]
@vinay961861 Heads up on a related issue: https://github.com/curiouslearning/FeedTheMonsterH5P/issues/77

You should only be able to progress to the next level if you get 2 or more stars.
