### ISSUE TITLE
In some levels there is no option matching the letter in prompt.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterH5P#73]
**Describe the bug**
In some Letteronly and LetterInWord levels (Level 15,22) there is no matching option for the letter in prompt.
**To Reproduce**

1. Start the Apache and MySQL server and open the localhost.
2. In the Curious Learning content go to Feed the Monster game and click on play button.
3. Click on developer mode and go to level selection screen and play the game.

**Expected behavior**
Proper answer option should be present in the stones which are matching with the letter in prompt.
**Screenshots**
![Screenshot (108).png](https://images.zenhubusercontent.com/623b0e5da1bf54266c59b5e8/eb955e2a-2544-49c3-84cb-02cfb2865ba8)
![Screenshot (109).png](https://images.zenhubusercontent.com/623b0e5da1bf54266c59b5e8/be7763a1-f6aa-4d1f-a7e7-7b4dd0a4ffdf)
**Desktop (please complete the following information):**
• OS: Windows 10
• Browser: Chrome
• Version: N/A
**Additional context**
N/A (edited)

**Comment by burrage** [comment]
I found this in level 4 as well (v30):
![Image from iOS](https://user-images.githubusercontent.com/5167186/169116989-94cf878b-c47e-4adf-92d6-523f81c67513.jpg)
