### ISSUE TITLE
Lock game in portrait mode

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterH5P#86]

**Comment by burrage** [comment]
@amitsinghsutara "Rotate device" placeholder image can be downloaded in Slack or in this card:

https://github.com/curiouslearning/FeedTheMonsterH5P/issues/99

Let me know if you need a non-transparent background or anything like that.

**Comment by amitsinghsutara** [comment]
@burrage ,
Sure will do,
Thanks a lot.
